/*
 * TelstraMessagingAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TelstraMessagingAPI.Standard;
using TelstraMessagingAPI.Standard.Utilities;


namespace TelstraMessagingAPI.Standard.Models
{
    public class OutboundPollResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string to;
        private string receivedTimestamp;
        private string sentTimestamp;
        private Models.StatusEnum? deliveryStatus;

        /// <summary>
        /// The phone number (recipient) the message was sent to (in E.164
        /// format).
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// The date and time when the message was recieved by recipient.
        /// </summary>
        [JsonProperty("receivedTimestamp")]
        public string ReceivedTimestamp 
        { 
            get 
            {
                return this.receivedTimestamp; 
            } 
            set 
            {
                this.receivedTimestamp = value;
                onPropertyChanged("ReceivedTimestamp");
            }
        }

        /// <summary>
        /// The date and time when the message was sent.
        /// </summary>
        [JsonProperty("sentTimestamp")]
        public string SentTimestamp 
        { 
            get 
            {
                return this.sentTimestamp; 
            } 
            set 
            {
                this.sentTimestamp = value;
                onPropertyChanged("SentTimestamp");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deliveryStatus", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.StatusEnum? DeliveryStatus 
        { 
            get 
            {
                return this.deliveryStatus; 
            } 
            set 
            {
                this.deliveryStatus = value;
                onPropertyChanged("DeliveryStatus");
            }
        }
    }
} 