/*
 * TelstraMessagingAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TelstraMessagingAPI.Standard;
using TelstraMessagingAPI.Standard.Utilities;


namespace TelstraMessagingAPI.Standard.Models
{
    public class SendMMSRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string mfrom;
        private string to;
        private string subject;
        private bool replyRequest;
        private List<Models.MMSContent> mMSContent;

        /// <summary>
        /// This will be the source address that will be displayed on the
        /// receiving device. If it is not present then it will default to the MSISDN
        /// assigned to the app. If replyRequest is set to true, then this field will
        /// be ignored.
        /// </summary>
        [JsonProperty("from")]
        public string From 
        { 
            get 
            {
                return this.mfrom; 
            } 
            set 
            {
                this.mfrom = value;
                onPropertyChanged("From");
            }
        }

        /// <summary>
        /// This is the destination address.
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// The subject that will be used in an MMS message.
        /// </summary>
        [JsonProperty("subject")]
        public string Subject 
        { 
            get 
            {
                return this.subject; 
            } 
            set 
            {
                this.subject = value;
                onPropertyChanged("Subject");
            }
        }

        /// <summary>
        /// If set to true, the reply message functionality will be implemented
        /// and the to address will be ignored if present.
        /// </summary>
        [JsonProperty("replyRequest")]
        public bool ReplyRequest 
        { 
            get 
            {
                return this.replyRequest; 
            } 
            set 
            {
                this.replyRequest = value;
                onPropertyChanged("ReplyRequest");
            }
        }

        /// <summary>
        /// An Array of content that will be sent in an MMS message. If this
        /// array is present it will cause the “body” element to be ignored, and the
        /// message will be sent as an MMS.
        /// </summary>
        [JsonProperty("MMSContent")]
        public List<Models.MMSContent> MMSContent 
        { 
            get 
            {
                return this.mMSContent; 
            } 
            set 
            {
                this.mMSContent = value;
                onPropertyChanged("MMSContent");
            }
        }
    }
} 