FROM microsoft/dotnet:2.2-sdk

WORKDIR /telstradev
COPY . .

RUN dotnet build 

WORKDIR /telstradev/src/Telstra.Messaging.Test
RUN dotnet test

WORKDIR /telstradev/src/Telstra.Messaging.BackwardCompatTest
CMD dotnet run