/* 
 * Telstra Messaging API
 *
 *  The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 
 *
 * OpenAPI spec version: 2.2.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using com.telstra.messaging.Client;
using com.telstra.messaging.Model;

namespace com.telstra.messaging.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProvisioningApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Subscription
        /// </summary>
        /// <remarks>
        /// Provision a mobile number
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <param name="body">A JSON payload containing the required attributes</param>
        /// <returns>ProvisionNumberResponse</returns>
        ProvisionNumberResponse CreateSubscription (string authorization, ProvisionNumberRequest body);

        /// <summary>
        /// Create Subscription
        /// </summary>
        /// <remarks>
        /// Provision a mobile number
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <param name="body">A JSON payload containing the required attributes</param>
        /// <returns>ApiResponse of ProvisionNumberResponse</returns>
        ApiResponse<ProvisionNumberResponse> CreateSubscriptionWithHttpInfo (string authorization, ProvisionNumberRequest body);
        /// <summary>
        /// Delete Subscription
        /// </summary>
        /// <remarks>
        /// Delete a mobile number subscription from an account
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns></returns>
        void DeleteSubscription (string authorization);

        /// <summary>
        /// Delete Subscription
        /// </summary>
        /// <remarks>
        /// Delete a mobile number subscription from an account
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteSubscriptionWithHttpInfo (string authorization);
        /// <summary>
        /// Get Subscription
        /// </summary>
        /// <remarks>
        /// Get mobile number subscription for an account
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>List&lt;ProvisionNumberResponse&gt;</returns>
        List<ProvisionNumberResponse> GetSubscription (string authorization);

        /// <summary>
        /// Get Subscription
        /// </summary>
        /// <remarks>
        /// Get mobile number subscription for an account
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>ApiResponse of List&lt;ProvisionNumberResponse&gt;</returns>
        ApiResponse<List<ProvisionNumberResponse>> GetSubscriptionWithHttpInfo (string authorization);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create Subscription
        /// </summary>
        /// <remarks>
        /// Provision a mobile number
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <param name="body">A JSON payload containing the required attributes</param>
        /// <returns>Task of ProvisionNumberResponse</returns>
        System.Threading.Tasks.Task<ProvisionNumberResponse> CreateSubscriptionAsync (string authorization, ProvisionNumberRequest body);

        /// <summary>
        /// Create Subscription
        /// </summary>
        /// <remarks>
        /// Provision a mobile number
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <param name="body">A JSON payload containing the required attributes</param>
        /// <returns>Task of ApiResponse (ProvisionNumberResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProvisionNumberResponse>> CreateSubscriptionAsyncWithHttpInfo (string authorization, ProvisionNumberRequest body);
        /// <summary>
        /// Delete Subscription
        /// </summary>
        /// <remarks>
        /// Delete a mobile number subscription from an account
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteSubscriptionAsync (string authorization);

        /// <summary>
        /// Delete Subscription
        /// </summary>
        /// <remarks>
        /// Delete a mobile number subscription from an account
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteSubscriptionAsyncWithHttpInfo (string authorization);
        /// <summary>
        /// Get Subscription
        /// </summary>
        /// <remarks>
        /// Get mobile number subscription for an account
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>Task of List&lt;ProvisionNumberResponse&gt;</returns>
        System.Threading.Tasks.Task<List<ProvisionNumberResponse>> GetSubscriptionAsync (string authorization);

        /// <summary>
        /// Get Subscription
        /// </summary>
        /// <remarks>
        /// Get mobile number subscription for an account
        /// </remarks>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>Task of ApiResponse (List&lt;ProvisionNumberResponse&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ProvisionNumberResponse>>> GetSubscriptionAsyncWithHttpInfo (string authorization);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ProvisioningApi : IProvisioningApi
    {
        private com.telstra.messaging.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProvisioningApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProvisioningApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = com.telstra.messaging.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProvisioningApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ProvisioningApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = com.telstra.messaging.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public com.telstra.messaging.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create Subscription Provision a mobile number
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <param name="body">A JSON payload containing the required attributes</param>
        /// <returns>ProvisionNumberResponse</returns>
        public ProvisionNumberResponse CreateSubscription (string authorization, ProvisionNumberRequest body)
        {
             ApiResponse<ProvisionNumberResponse> localVarResponse = CreateSubscriptionWithHttpInfo(authorization, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create Subscription Provision a mobile number
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <param name="body">A JSON payload containing the required attributes</param>
        /// <returns>ApiResponse of ProvisionNumberResponse</returns>
        public ApiResponse< ProvisionNumberResponse > CreateSubscriptionWithHttpInfo (string authorization, ProvisionNumberRequest body)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ProvisioningApi->CreateSubscription");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ProvisioningApi->CreateSubscription");

            var localVarPath = "/messages/provisioning/subscriptions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (auth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateSubscription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ProvisionNumberResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ProvisionNumberResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ProvisionNumberResponse)));
        }

        /// <summary>
        /// Create Subscription Provision a mobile number
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <param name="body">A JSON payload containing the required attributes</param>
        /// <returns>Task of ProvisionNumberResponse</returns>
        public async System.Threading.Tasks.Task<ProvisionNumberResponse> CreateSubscriptionAsync (string authorization, ProvisionNumberRequest body)
        {
             ApiResponse<ProvisionNumberResponse> localVarResponse = await CreateSubscriptionAsyncWithHttpInfo(authorization, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create Subscription Provision a mobile number
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <param name="body">A JSON payload containing the required attributes</param>
        /// <returns>Task of ApiResponse (ProvisionNumberResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ProvisionNumberResponse>> CreateSubscriptionAsyncWithHttpInfo (string authorization, ProvisionNumberRequest body)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ProvisioningApi->CreateSubscription");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ProvisioningApi->CreateSubscription");

            var localVarPath = "/messages/provisioning/subscriptions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (auth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateSubscription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ProvisionNumberResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ProvisionNumberResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ProvisionNumberResponse)));
        }

        /// <summary>
        /// Delete Subscription Delete a mobile number subscription from an account
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns></returns>
        public void DeleteSubscription (string authorization)
        {
             DeleteSubscriptionWithHttpInfo(authorization);
        }

        /// <summary>
        /// Delete Subscription Delete a mobile number subscription from an account
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteSubscriptionWithHttpInfo (string authorization)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ProvisioningApi->DeleteSubscription");

            var localVarPath = "/messages/provisioning/subscriptions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (auth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteSubscription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete Subscription Delete a mobile number subscription from an account
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteSubscriptionAsync (string authorization)
        {
             await DeleteSubscriptionAsyncWithHttpInfo(authorization);

        }

        /// <summary>
        /// Delete Subscription Delete a mobile number subscription from an account
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteSubscriptionAsyncWithHttpInfo (string authorization)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ProvisioningApi->DeleteSubscription");

            var localVarPath = "/messages/provisioning/subscriptions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (auth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteSubscription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get Subscription Get mobile number subscription for an account
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>List&lt;ProvisionNumberResponse&gt;</returns>
        public List<ProvisionNumberResponse> GetSubscription (string authorization)
        {
             ApiResponse<List<ProvisionNumberResponse>> localVarResponse = GetSubscriptionWithHttpInfo(authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Subscription Get mobile number subscription for an account
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>ApiResponse of List&lt;ProvisionNumberResponse&gt;</returns>
        public ApiResponse< List<ProvisionNumberResponse> > GetSubscriptionWithHttpInfo (string authorization)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ProvisioningApi->GetSubscription");

            var localVarPath = "/messages/provisioning/subscriptions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (auth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSubscription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ProvisionNumberResponse>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ProvisionNumberResponse>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ProvisionNumberResponse>)));
        }

        /// <summary>
        /// Get Subscription Get mobile number subscription for an account
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>Task of List&lt;ProvisionNumberResponse&gt;</returns>
        public async System.Threading.Tasks.Task<List<ProvisionNumberResponse>> GetSubscriptionAsync (string authorization)
        {
             ApiResponse<List<ProvisionNumberResponse>> localVarResponse = await GetSubscriptionAsyncWithHttpInfo(authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Subscription Get mobile number subscription for an account
        /// </summary>
        /// <exception cref="com.telstra.messaging.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.</param>
        /// <returns>Task of ApiResponse (List&lt;ProvisionNumberResponse&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ProvisionNumberResponse>>> GetSubscriptionAsyncWithHttpInfo (string authorization)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ProvisioningApi->GetSubscription");

            var localVarPath = "/messages/provisioning/subscriptions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (auth) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSubscription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ProvisionNumberResponse>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ProvisionNumberResponse>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ProvisionNumberResponse>)));
        }

    }
}
