/* 
 * Telstra Messaging API
 *
 *  The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 
 *
 * OpenAPI spec version: 2.2.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.telstra.messaging.Api;
using com.telstra.messaging.Model;
using com.telstra.messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.telstra.messaging.Test
{
    /// <summary>
    ///  Class for testing DeleteNumberRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeleteNumberRequestTests
    {
        // TODO uncomment below to declare an instance variable for DeleteNumberRequest
        //private DeleteNumberRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeleteNumberRequest
            //instance = new DeleteNumberRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeleteNumberRequest
        /// </summary>
        [Test]
        public void DeleteNumberRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeleteNumberRequest
            //Assert.IsInstanceOfType<DeleteNumberRequest> (instance, "variable 'instance' is a DeleteNumberRequest");
        }


        /// <summary>
        /// Test the property 'EmptyArr'
        /// </summary>
        [Test]
        public void EmptyArrTest()
        {
            // TODO unit test for the property 'EmptyArr'
        }

    }

}
