/* 
 * Telstra Messaging API
 *
 *  The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 
 *
 * OpenAPI spec version: 2.2.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.telstra.messaging.Api;
using com.telstra.messaging.Model;
using com.telstra.messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.telstra.messaging.Test
{
    /// <summary>
    ///  Class for testing InboundPollResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InboundPollResponseTests
    {
        // TODO uncomment below to declare an instance variable for InboundPollResponse
        //private InboundPollResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InboundPollResponse
            //instance = new InboundPollResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InboundPollResponse
        /// </summary>
        [Test]
        public void InboundPollResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InboundPollResponse
            //Assert.IsInstanceOfType<InboundPollResponse> (instance, "variable 'instance' is a InboundPollResponse");
        }


        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'ReceivedTimestamp'
        /// </summary>
        [Test]
        public void ReceivedTimestampTest()
        {
            // TODO unit test for the property 'ReceivedTimestamp'
        }
        /// <summary>
        /// Test the property 'MoreMessages'
        /// </summary>
        [Test]
        public void MoreMessagesTest()
        {
            // TODO unit test for the property 'MoreMessages'
        }
        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Test]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }

    }

}
