/* 
 * Telstra Messaging API
 *
 *  The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 
 *
 * OpenAPI spec version: 2.2.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.telstra.messaging.Api;
using com.telstra.messaging.Model;
using com.telstra.messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.telstra.messaging.Test
{
    /// <summary>
    ///  Class for testing OAuthResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OAuthResponseTests
    {
        // TODO uncomment below to declare an instance variable for OAuthResponse
        //private OAuthResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OAuthResponse
            //instance = new OAuthResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OAuthResponse
        /// </summary>
        [Test]
        public void OAuthResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OAuthResponse
            //Assert.IsInstanceOfType<OAuthResponse> (instance, "variable 'instance' is a OAuthResponse");
        }


        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Test]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Test]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Test]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

    }

}
