/* 
 * Telstra Messaging API
 *
 *  The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 
 *
 * OpenAPI spec version: 2.2.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.telstra.messaging.Api;
using com.telstra.messaging.Model;
using com.telstra.messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.telstra.messaging.Test
{
    /// <summary>
    ///  Class for testing OAuthRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OAuthRequestTests
    {
        // TODO uncomment below to declare an instance variable for OAuthRequest
        //private OAuthRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OAuthRequest
            //instance = new OAuthRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OAuthRequest
        /// </summary>
        [Test]
        public void OAuthRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OAuthRequest
            //Assert.IsInstanceOfType<OAuthRequest> (instance, "variable 'instance' is a OAuthRequest");
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'ClientSecret'
        /// </summary>
        [Test]
        public void ClientSecretTest()
        {
            // TODO unit test for the property 'ClientSecret'
        }
        /// <summary>
        /// Test the property 'GrantType'
        /// </summary>
        [Test]
        public void GrantTypeTest()
        {
            // TODO unit test for the property 'GrantType'
        }
        /// <summary>
        /// Test the property 'Scopes'
        /// </summary>
        [Test]
        public void ScopesTest()
        {
            // TODO unit test for the property 'Scopes'
        }

    }

}
