/* 
 * Telstra Messaging API
 *
 *  The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 
 *
 * OpenAPI spec version: 2.2.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.telstra.messaging.Api;
using com.telstra.messaging.Model;
using com.telstra.messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.telstra.messaging.Test
{
    /// <summary>
    ///  Class for testing OutboundPollResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OutboundPollResponseTests
    {
        // TODO uncomment below to declare an instance variable for OutboundPollResponse
        //private OutboundPollResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OutboundPollResponse
            //instance = new OutboundPollResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OutboundPollResponse
        /// </summary>
        [Test]
        public void OutboundPollResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OutboundPollResponse
            //Assert.IsInstanceOfType<OutboundPollResponse> (instance, "variable 'instance' is a OutboundPollResponse");
        }


        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'ReceivedTimestamp'
        /// </summary>
        [Test]
        public void ReceivedTimestampTest()
        {
            // TODO unit test for the property 'ReceivedTimestamp'
        }
        /// <summary>
        /// Test the property 'SentTimestamp'
        /// </summary>
        [Test]
        public void SentTimestampTest()
        {
            // TODO unit test for the property 'SentTimestamp'
        }
        /// <summary>
        /// Test the property 'DeliveryStatus'
        /// </summary>
        [Test]
        public void DeliveryStatusTest()
        {
            // TODO unit test for the property 'DeliveryStatus'
        }

    }

}
