/* 
 * Telstra Messaging API
 *
 *  The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 
 *
 * OpenAPI spec version: 2.2.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.telstra.messaging.Api;
using com.telstra.messaging.Model;
using com.telstra.messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.telstra.messaging.Test
{
    /// <summary>
    ///  Class for testing ProvisionNumberRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProvisionNumberRequestTests
    {
        // TODO uncomment below to declare an instance variable for ProvisionNumberRequest
        //private ProvisionNumberRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProvisionNumberRequest
            //instance = new ProvisionNumberRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProvisionNumberRequest
        /// </summary>
        [Test]
        public void ProvisionNumberRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProvisionNumberRequest
            //Assert.IsInstanceOfType<ProvisionNumberRequest> (instance, "variable 'instance' is a ProvisionNumberRequest");
        }


        /// <summary>
        /// Test the property 'ActiveDays'
        /// </summary>
        [Test]
        public void ActiveDaysTest()
        {
            // TODO unit test for the property 'ActiveDays'
        }
        /// <summary>
        /// Test the property 'NotifyURL'
        /// </summary>
        [Test]
        public void NotifyURLTest()
        {
            // TODO unit test for the property 'NotifyURL'
        }

    }

}
