/* 
 * Telstra Messaging API
 *
 *  The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 
 *
 * OpenAPI spec version: 2.2.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.telstra.messaging.Api;
using com.telstra.messaging.Model;
using com.telstra.messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.telstra.messaging.Test
{
    /// <summary>
    ///  Class for testing SendSMSRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SendSMSRequestTests
    {
        // TODO uncomment below to declare an instance variable for SendSMSRequest
        //private SendSMSRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SendSMSRequest
            //instance = new SendSMSRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SendSMSRequest
        /// </summary>
        [Test]
        public void SendSMSRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SendSMSRequest
            //Assert.IsInstanceOfType<SendSMSRequest> (instance, "variable 'instance' is a SendSMSRequest");
        }


        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Validity'
        /// </summary>
        [Test]
        public void ValidityTest()
        {
            // TODO unit test for the property 'Validity'
        }
        /// <summary>
        /// Test the property 'ScheduledDelivery'
        /// </summary>
        [Test]
        public void ScheduledDeliveryTest()
        {
            // TODO unit test for the property 'ScheduledDelivery'
        }
        /// <summary>
        /// Test the property 'NotifyURL'
        /// </summary>
        [Test]
        public void NotifyURLTest()
        {
            // TODO unit test for the property 'NotifyURL'
        }
        /// <summary>
        /// Test the property 'ReplyRequest'
        /// </summary>
        [Test]
        public void ReplyRequestTest()
        {
            // TODO unit test for the property 'ReplyRequest'
        }

    }

}
