/* 
 * Telstra Messaging API
 *
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telstra.Messaging.Api;
using Telstra.Messaging.Model;
using Telstra.Messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telstra.Messaging.Test
{
    /// <summary>
    ///  Class for testing DeleteNumberRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeleteNumberRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeleteNumberRequest
        //private DeleteNumberRequest instance;

        public DeleteNumberRequestTests()
        {
            // TODO uncomment below to create an instance of DeleteNumberRequest
            //instance = new DeleteNumberRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeleteNumberRequest
        /// </summary>
        [Fact]
        public void DeleteNumberRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeleteNumberRequest
            //Assert.IsInstanceOfType<DeleteNumberRequest> (instance, "variable 'instance' is a DeleteNumberRequest");
        }


        /// <summary>
        /// Test the property 'EmptyArr'
        /// </summary>
        [Fact]
        public void EmptyArrTest()
        {
            // TODO unit test for the property 'EmptyArr'
        }

    }

}
