/* 
 * Telstra Messaging API
 *
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telstra.Messaging.Api;
using Telstra.Messaging.Model;
using Telstra.Messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telstra.Messaging.Test
{
    /// <summary>
    ///  Class for testing GetMmsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMmsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMmsResponse
        //private GetMmsResponse instance;

        public GetMmsResponseTests()
        {
            // TODO uncomment below to create an instance of GetMmsResponse
            //instance = new GetMmsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMmsResponse
        /// </summary>
        [Fact]
        public void GetMmsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetMmsResponse
            //Assert.IsInstanceOfType<GetMmsResponse> (instance, "variable 'instance' is a GetMmsResponse");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'DestinationAddress'
        /// </summary>
        [Fact]
        public void DestinationAddressTest()
        {
            // TODO unit test for the property 'DestinationAddress'
        }
        /// <summary>
        /// Test the property 'SenderAddress'
        /// </summary>
        [Fact]
        public void SenderAddressTest()
        {
            // TODO unit test for the property 'SenderAddress'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }
        /// <summary>
        /// Test the property 'ApiMsgId'
        /// </summary>
        [Fact]
        public void ApiMsgIdTest()
        {
            // TODO unit test for the property 'ApiMsgId'
        }
        /// <summary>
        /// Test the property 'SentTimestamp'
        /// </summary>
        [Fact]
        public void SentTimestampTest()
        {
            // TODO unit test for the property 'SentTimestamp'
        }
        /// <summary>
        /// Test the property 'MMSContent'
        /// </summary>
        [Fact]
        public void MMSContentTest()
        {
            // TODO unit test for the property 'MMSContent'
        }

    }

}
