/* 
 * Telstra Messaging API
 *
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telstra.Messaging.Api;
using Telstra.Messaging.Model;
using Telstra.Messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telstra.Messaging.Test
{
    /// <summary>
    ///  Class for testing HealthCheckResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HealthCheckResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HealthCheckResponse
        //private HealthCheckResponse instance;

        public HealthCheckResponseTests()
        {
            // TODO uncomment below to create an instance of HealthCheckResponse
            //instance = new HealthCheckResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthCheckResponse
        /// </summary>
        [Fact]
        public void HealthCheckResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HealthCheckResponse
            //Assert.IsInstanceOfType<HealthCheckResponse> (instance, "variable 'instance' is a HealthCheckResponse");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
