/* 
 * Telstra Messaging API
 *
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telstra.Messaging.Api;
using Telstra.Messaging.Model;
using Telstra.Messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telstra.Messaging.Test
{
    /// <summary>
    ///  Class for testing MessageSentResponseMms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageSentResponseMmsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessageSentResponseMms
        //private MessageSentResponseMms instance;

        public MessageSentResponseMmsTests()
        {
            // TODO uncomment below to create an instance of MessageSentResponseMms
            //instance = new MessageSentResponseMms();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageSentResponseMms
        /// </summary>
        [Fact]
        public void MessageSentResponseMmsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessageSentResponseMms
            //Assert.IsInstanceOfType<MessageSentResponseMms> (instance, "variable 'instance' is a MessageSentResponseMms");
        }


        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'MmsMediaKB'
        /// </summary>
        [Fact]
        public void MmsMediaKBTest()
        {
            // TODO unit test for the property 'MmsMediaKB'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }
        /// <summary>
        /// Test the property 'NumberSegments'
        /// </summary>
        [Fact]
        public void NumberSegmentsTest()
        {
            // TODO unit test for the property 'NumberSegments'
        }

    }

}
