/* 
 * Telstra Messaging API
 *
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telstra.Messaging.Api;
using Telstra.Messaging.Model;
using Telstra.Messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telstra.Messaging.Test
{
    /// <summary>
    ///  Class for testing OAuthResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OAuthResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OAuthResponse
        //private OAuthResponse instance;

        public OAuthResponseTests()
        {
            // TODO uncomment below to create an instance of OAuthResponse
            //instance = new OAuthResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OAuthResponse
        /// </summary>
        [Fact]
        public void OAuthResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OAuthResponse
            //Assert.IsInstanceOfType<OAuthResponse> (instance, "variable 'instance' is a OAuthResponse");
        }


        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

    }

}
