/* 
 * Telstra Messaging API
 *
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telstra.Messaging.Api;
using Telstra.Messaging.Model;
using Telstra.Messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telstra.Messaging.Test
{
    /// <summary>
    ///  Class for testing ProvisionNumberResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProvisionNumberResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProvisionNumberResponse
        //private ProvisionNumberResponse instance;

        public ProvisionNumberResponseTests()
        {
            // TODO uncomment below to create an instance of ProvisionNumberResponse
            //instance = new ProvisionNumberResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProvisionNumberResponse
        /// </summary>
        [Fact]
        public void ProvisionNumberResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProvisionNumberResponse
            //Assert.IsInstanceOfType<ProvisionNumberResponse> (instance, "variable 'instance' is a ProvisionNumberResponse");
        }


        /// <summary>
        /// Test the property 'DestinationAddress'
        /// </summary>
        [Fact]
        public void DestinationAddressTest()
        {
            // TODO unit test for the property 'DestinationAddress'
        }
        /// <summary>
        /// Test the property 'ExpiryDate'
        /// </summary>
        [Fact]
        public void ExpiryDateTest()
        {
            // TODO unit test for the property 'ExpiryDate'
        }

    }

}
