/* 
 * Telstra Messaging API
 *
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telstra.Messaging.Api;
using Telstra.Messaging.Model;
using Telstra.Messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telstra.Messaging.Test
{
    /// <summary>
    ///  Class for testing SendSMSRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendSMSRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendSMSRequest
        //private SendSMSRequest instance;

        public SendSMSRequestTests()
        {
            // TODO uncomment below to create an instance of SendSMSRequest
            //instance = new SendSMSRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendSMSRequest
        /// </summary>
        [Fact]
        public void SendSMSRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SendSMSRequest
            //Assert.IsInstanceOfType<SendSMSRequest> (instance, "variable 'instance' is a SendSMSRequest");
        }


        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Validity'
        /// </summary>
        [Fact]
        public void ValidityTest()
        {
            // TODO unit test for the property 'Validity'
        }
        /// <summary>
        /// Test the property 'ScheduledDelivery'
        /// </summary>
        [Fact]
        public void ScheduledDeliveryTest()
        {
            // TODO unit test for the property 'ScheduledDelivery'
        }
        /// <summary>
        /// Test the property 'NotifyURL'
        /// </summary>
        [Fact]
        public void NotifyURLTest()
        {
            // TODO unit test for the property 'NotifyURL'
        }
        /// <summary>
        /// Test the property 'ReplyRequest'
        /// </summary>
        [Fact]
        public void ReplyRequestTest()
        {
            // TODO unit test for the property 'ReplyRequest'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

    }

}
