/* 
 * Telstra Messaging API
 *
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telstra.Messaging.Api;
using Telstra.Messaging.Model;
using Telstra.Messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telstra.Messaging.Test
{
    /// <summary>
    ///  Class for testing Status
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Status
        //private Status instance;

        public StatusTests()
        {
            // TODO uncomment below to create an instance of Status
            //instance = new Status();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Status
        /// </summary>
        [Fact]
        public void StatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Status
            //Assert.IsInstanceOfType<Status> (instance, "variable 'instance' is a Status");
        }



    }

}
